import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const satochi = localFont({
  src: [
    {
      path: "../fonts/satochi/Satoshi-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/satochi/Satoshi-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/satochi/Satoshi-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-Satoshi",
  display: "swap",
});

const integralCF = localFont({
  src: [
    {
      path: "../fonts/integralCf/integralcf-bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-IntegralCF",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satochi.variable} ${integralCF.variable} bg-red-600 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
